name: Generate Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install matplotlib pandas

      - name: Generate chart
        run: python scripts/generate_chart.py

      - name: Commit and push chart
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/chart.png
          git commit -m "Generated chart"
          git push
