name: Data Cleaning Pipeline

on: [push, pull_request]

jobs:
  clean-and-test-data:
    runs-on: ubuntu-latest

    steps:
      - name: Repo kloonimine
        uses: actions/checkout@v3

      - name: Python'i seadistamine
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Vajalike pakettide installimine
        run: pip install pandas

      - name: Testide jooksutamine
        run: python -m unittest discover tests

      - name: Andmete puhastamine
        run: python data/process_data.py

      - name: CSV-faili üleslaadimine artefaktina
        uses: actions/upload-artifact@v3
        with:
          name: cleaned-data
          path: data/cleaned_lahendid.csv

      - name: Installi vajalikud Python'i paketid
        run: pip install pandas networkx matplotlib

      - name: Andmete puhastamine ja visualiseerimine
        run: python data/process_data.py
        
      - name: Salvesta joonis artefaktina
        uses: actions/upload-artifact@v3
        with:
          name: kohtulahendite-graaf
          path: data/lahendid_graph.png
