name: Generate Chart

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"  # Jookseb igal esmaspäeval

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Klooni repo
        uses: actions/checkout@v3

      - name: Installi Python ja Pandas
        run: |
          sudo apt-get install python3-matplotlib
          pip install pandas matplotlib

      - name: Käivita Pythoni skript
        run: python scripts/process_data.py

      - name: Laadi üles uuendatud graafik
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/chart.png
          git commit -m "Uuendatud graafik"
          git push
