name: Genereeri ja uuenda graafik

on:
  push:
    paths:
      - "data/kohtulahendid.csv"
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  generate-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAG }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install pandas matplotlib
      - run: python scripts/generate_chart.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Uuendatud graafik"
          file_pattern: "docs/chart.png"
          token: ${{ secrets.MAG }}
