name: Genereeri ja uuenda graafik

on:
  push:
    paths:
      - "data/kohtulahendid.csv"  # Käivitub ainult siis, kui CSV muutub
  schedule:
    - cron: '0 0 * * 1'  # Käivitab igal esmaspäeval kell 00:00 UTC
  workflow_dispatch:  # Võimaldab käsitsi käivitada

jobs:
  generate-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Klooni repositoorium
        uses: actions/checkout@v3

      - name: Paigalda Python ja sõltuvused
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installi Pandas ja Matplotlib
        run: pip install pandas matplotlib

      - name: Käivita skript ja loo graafik
        run: python scripts/generate_chart.py

      - name: Kontrolli, kas graafik on loodud
        run: |
          echo "📂 Kontrollin kausta sisu:"
          ls -lah docs/
          echo "🖼 Faili tüüp:"
          file docs/chart.png || echo "❌ Graafikut ei leitud!"

      - name: Commiti ja pushi uus graafik
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com
